# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='personal_list',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 13, 6, 20, 66144)),
        ),
        migrations.AddField(
            model_name='personal_list',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personal_list',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personal_list',
            name='title',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
