# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180917_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_list',
            name='summary',
        ),
        migrations.AlterField(
            model_name='personal_list',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 13, 6, 47, 798282)),
        ),
    ]
