# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20180917_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_priority', models.IntegerField(default=0)),
                ('description_priority', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_state', models.IntegerField(default=0)),
                ('description_state', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='personal_list',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 14, 30, 38, 544388)),
        ),
        migrations.AlterField(
            model_name='personal_list',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personal_list',
            name='priority',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='lists.Priority'),
        ),
        migrations.AddField(
            model_name='personal_list',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='state', to='lists.State'),
        ),
    ]
