# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20180917_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_list',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 14, 40, 21, 468587)),
        ),
        migrations.AlterField(
            model_name='personal_list',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='lists.Priority'),
        ),
        migrations.AlterField(
            model_name='personal_list',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='lists.State'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='description_priority',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='number_priority',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
