# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 21:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180917_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_list',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 18, 39, 53, 797200)),
        ),
        migrations.AlterField(
            model_name='personal_list',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Priority'),
        ),
        migrations.AlterField(
            model_name='personal_list',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.State'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='number_priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='description_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='number_state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
