# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20180917_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_list',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 20, 42, 46, 775066)),
        ),
    ]
